[pytest]
DJANGO_SETTINGS_MODULE = gateway_ms.settings_test
python_files = tests/test_*.py tests/**/test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    -v
    --cov=core
    --cov=auth_oidc
    --cov=auth_legacy
    --cov=m2m
    --cov-report=term-missing
    --cov-fail-under=90
